### PR TITLE
Modified README and added my name

### PR DESCRIPTION
**Pull request by dalshekerchi**
- added bullet point

### CODE REVIEW

**Review by Leo6Leo — CHANGES_REQUESTED** [review]
Hey Dana, it seems like there is a conflict between your commit and the commit of others. Take a look at the description in Notion, and see how to resolve the conflict correctly.

**Review by Mustaballer — APPROVED** [review]

**Review by lukecheseldine — APPROVED** [review]
Hi Dana, looks good :)

**Review by Leo6Leo — APPROVED** [review]
Great Work Dana! You can merge it rn!!

**Comment by YuYing-Liang** [comment]
@dalshekerchi try to name your branches more specifically "adding-my-name-to-readme" could be anyone's name, not a huge problem now but practice clearer naming in the future

**Pull request merged**
